services:
  frontend:
    build:
      context: .
      args:
        - NEXT_PUBLIC_API_URL=http://jobchaja.com:8000
        - BACKEND_URL=http://job-backend:8000
    container_name: job-frontend
    environment:
      - BACKEND_URL=http://job-backend:8000
    networks:
      - default
      - backend-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
    networks:
      - default
      - backend-network

networks:
  default:
  backend-network:
    external: true
    name: job-platform-backend_default
